# your_app_name/templatetags/custom_filters.py

from django import template

# IMPORTANT: You must register your library instance
register = template.Library()

@register.filter
def get_count(summary_list, key):
    """
    Looks up the count for a specific status or priority key (e.g., 'DONE', 'HIGH') 
    in a list of dictionaries generated by Django's annotate function.
    
    Example usage in template: {{ status_summary|get_count:'DONE' }}
    """
    if not summary_list:
        return 0
        
    for item in summary_list:
        # We check both 'status' and 'priority' keys because the summary list 
        # might contain either based on whether you passed status_summary or priority_summary.
        
        # Check if the dictionary has a 'status' key matching the input key
        if item.get('status') == key:
            return item.get('count', 0)
            
        # Check if the dictionary has a 'priority' key matching the input key
        elif item.get('priority') == key:
            return item.get('count', 0)
            
    # Return 0 if the key is not found in any dictionary
    return 0